### ISSUE TITLE
Update openwrt script to support later releases

### ISSUE THREAD

**Issue by plajjan** [vrnetlab/vrnetlab#205]
The download script for openwrt tries to find a combined-ext4.img.gz file in a x86/kvm_guest directory. Only releases up to 15.05 used this structure. From 17.01 and newer there is no longer a special image for being a kvm-guest, instead the standard image also supports being a KVM guest. To support downloading these we need to check the version and then assume a different directory, for example for 18.06.4 it is https://downloads.openwrt.org/releases/18.06.4/targets/x86/64/ - so it's `/64` at the end, instead of `/kvm_guest`. In there we find the combined-ext4.img.gz as usual.

I wonder if I could interest you, @enukane, in writing this, seeing how you recently fixed other parts of that script? :)

**Comment by mzagozen** [comment]
Fix in f6461ec5d25c9fc2e83a17406c8eb74a434a2695
