### ISSUE TITLE
vmx: invalid/obsolet option for qemu-kvm

### ISSUE THREAD

**Issue by tahir24434** [vrnetlab/vrnetlab#210]
Hi, Thanks for the useful project. While running 'make', I am getting below error

> 2019-09-19 22:21:22,667: vrnetlab   INFO     Starting VMX_vcp                                                                                                                                             
> 2019-09-19 22:21:22,667: vrnetlab   DEBUG    ['qemu-system-x86_64', '-display', 'none', '-machine', 'pc', '-monitor', 'tcp:0.0.0.0:4000,server,nowait', '-m', '2048', '-serial', 'telnet:0.0.0.0:5000,ser$
> er,nowait', '-drive', 'if=ide,file=/vmx/junos-vmx-x86-64-17.2X75-D105.9-overlay.qcow2', '-drive', 'if=ide,file=/vmx/vmxhdd.img', '-usb', '-usbdevice', 'disk:format=raw:/vmx/metadata-usb-re.img', '-smbi$
> s', 'type=0,vendor=Juniper', '-smbios', 'type=1,manufacturer=Juniper,product=VM-vcp_vmx2-161-re-0,version=0.1.0', '-device', 'e1000,netdev=p00,mac=52:54:00:1d:0c:00', '-netdev', 'user,id=p00,net=10.0.0$
> 0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443']                       
> 2019-09-19 22:21:23,064: vrnetlab   INFO     STDOUT:                                                                                                                                                      
**_> 2019-09-19 22:21:23,064: vrnetlab   INFO     STDERR: qemu-system-x86_64: -usbdevice disk:format=raw:/vmx/metadata-usb-re.img: '-usbdevice' is deprecated, please use '-device usb-...' instead_**
> qemu-system-x86_64: -usbdevice disk:format=raw:/vmx/metadata-usb-re.img: could not add USB device 'disk:format=raw:/vmx/metadata-usb-re.img'
> 
> 2019-09-19 22:21:23,066: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 1)

Please note that I'm running make on Ubuntu18.04 and my router device version is junos-vmx-x86-64-17.2X75-D105.9.qcow2.
Can you please tell me that with what qemu-kvm version we tested it?

**Comment by mzagozen** [comment]
Fixed with #211, thanks!
