### ISSUE TITLE
interface assign issue

### ISSUE THREAD

**Issue by little-pool** [vrnetlab/vrnetlab#217]
how can I assign how many interfaces existed into a 9kv?

**Comment by mzagozen** [comment]
Both _xrv9k_ and _nxos9kv_ support the standard `--num-nics X` argument. For example, to start _xrv9k_ with 48 NICs: `docker run -d --name xrv9k-big --privileged vrnetlab/vr-xrv9k:7.1.6 --num-nics 48 --trace`.
