### ISSUE TITLE
problem with docker run for Cisco nxos9kv 9300/9400 images

### ISSUE THREAD

**Issue by cnsphng** [vrnetlab/vrnetlab#271]
successfully make image for either Cisco 9300/9500 version 9.3.8 but when using docker run i got this message below:

me@ubuntu:~$ docker run -d --name nxos9kv1 --privileged nxos9kv:9.3.8
e7cba22692263bbf48b3c67bca9c4eb4ef1bd1c614687c86ed7e9c19dd2de24d
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/launch.py": permission denied: unknown.

this error happen with both 9300 and 9500.

thanks,!

**Comment by cnsphng** [comment]
i assume i need to run this command: docker run -it --rm --privileged nxos9kv:9.3.8 ls -la /launch.py

get exact same error:
me@ubuntu:~/vrnetlab/nxos9kv$ docker run -it --rm --privileged nxos9kv:9.3.8 ls -la /launch.py
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/launch.py": permission denied: unknown.
me@ubuntu:~/vrnetlab/nxos9kv$

**Comment by mzagozen** [comment]
@cnsphng is this sill a problem with the latest version? Recent CI runs show that launching an nxos9kv container works: https://github.com/vrnetlab/vrnetlab/actions/runs/5468090188/jobs/9955257050

**Comment by jay2496** [comment]
Did this ever get resolved? running into same issue. Did the chmod +x
