### ISSUE TITLE
NXOS - Cisco Nexus 9000v - boot stuck

### ISSUE THREAD

**Issue by lemontree61089** [vrnetlab/vrnetlab#302]
Hello,

I built an image using nexus9300v.9.3.10.qcow2. When trying to launch it, it is stuck with the following message:

`2023-01-12 10:55:36,248: vrnetlab   DEBUG    joined cmd: qemu-system-x86_64 -enable-kvm -display none -machine pc -monitor tcp:0.0.0.0:4000,server,nowait -m 4096 -serial telnet:0.0.0.0:5000,server,nowait -drive if=ide,file=/nxosv-7.2.0.D1.1-overlay.qcow2 -cpu host -smp 2 -device e1000,netdev=p00,mac=52:54:00:25:75:00 -netdev user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443`

Anyone has an idea ?

**Comment by plajjan** [comment]
Add `--trace` to `docker run .... --trace` and you'll get more output. That should be your first thing. I presume you are running with --privileged?

**Comment by mzagozen** [comment]
@lemontree61089 did you use the `nxos` directory or `nxos9k`? Your image name `nexus9300v.9.3.10.qcow2` suggests you should use `nxos9k`, but in the output you provided I see `nxosv-7.2.0.D1.1`.

As a datapoint, `nexus9300v.9.3.7.qcow2` works for us (built via `nxos9k`).

**Comment by juliencorsini** [comment]
> @lemontree61089 did you use the `nxos` directory or `nxos9k`? Your image name `nexus9300v.9.3.10.qcow2` suggests you should use `nxos9k`, but in the output you provided I see `nxosv-7.2.0.D1.1`.
> 
> As a datapoint, `nexus9300v.9.3.7.qcow2` works for us (built via `nxos9k`).

Hi there,
I confirm this. Image nexus9300v.9.3.11.qcow2 runs perfectly built as nxos9k.

```
REPOSITORY                        TAG       IMAGE ID       CREATED          SIZE
vrnetlab/vr-n9kv                  9.3.11    5aa94551568e   16 minutes ago   2.43GB

    Leaf1:
      kind: vr-n9kv
      image: vrnetlab/vr-n9kv:9.3.11
```
