### ISSUE TITLE
Can't launch Nx9k docker with containerlab

### ISSUE THREAD

**Issue by alfonsomoneo** [vrnetlab/vrnetlab#306]
Hello, first of all... thanks a lot for this amazing work.
I'm working with containerlab and Cisco NXOS 9K but after deploying the toplogy, the container fails in "exited" status.
Looking into log files, I've found the following messages:

usage: launch.py [-h] [--trace] [--username USERNAME] [--password PASSWORD]
                 [--bios BIOS] [--num-nics NUM_NICS]
launch.py: error: unrecognized arguments: --hostname compute_leaf_f2_23 --connection-mode tc

It seems containerlab try to send a hostname and connection-mode but default launch.py does not recognized these arguments.

Should I change anything else?

Thanks!

**Comment by hellt** [comment]
@alfonsomoneo 
for containerlab you have to use https://github.com/hellt/vrnetlab

**Comment by alfonsomoneo** [comment]
Thanks a lot Hellt, I will try it with hellt/vrnetlab then

**Comment by hellt** [comment]
you can use our discord for containerlab feedback, this is outside of vrnetlab https://containerlab.dev/community/

**Comment by mzagozen** [comment]
Closing as it refers to https://github.com/hellt/vrnetlab.
