### ISSUE TITLE
Cannot launch CSR w/IOS 17.03.05

### ISSUE THREAD

**Issue by bvilajol** [vrnetlab/vrnetlab#312]
Hello,

We're having some trouble to run a Cisco CSR1000v. Tested with both serial and non-serial images.

csr1000v-universalk9.17.03.05.efi.qcow2
csr1000v-universalk9.17.03.05-serial.efi.qcow2

Once connecting towards tcp/5000 (serial) socket is established but no output. 

root@acme:~/vrnetlab/csr# telnet -l admin 172.17.0.3 5000
Trying 172.17.0.3...
Connected to 172.17.0.3.
Escape character is '^]'.

If logging to the pod it looks device is "starting".

root@840464c8b452:/# uname -a
Linux 840464c8b452 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 GNU/Linux
root@840464c8b452:/# python3 healthcheck.py 
starting

Is 17.03.05 tested? compatible?

Thanks in advance for any input,

**Comment by plajjan** [comment]
Please provid the full command you use to start the container. Try including `--trace` as an argument (`docker run --privileged -it ... vr-csr... --trace`) and you should get more debug output

**Comment by bvilajol** [comment]
Hello,

thanks for answering. 

Repeated the process from a clean env. Just added tweak as per [here](https://github.com/vrnetlab/vrnetlab/discussions/300). Make process outputs two images, 

```
vrnetlab/vr-csr   17.03.05   2869d2cf5331   About a minute ago   2.4GB
<none>            <none>     ba5d7e83bee3   5 minutes ago        2.35GB
```

, but got it  working. Sorry for the issue.

And thanks for the work, 

B,


Boot
=
  Booting `CSR1000v - packages.conf'


BOOT CMD: /packages.conf rw root=/dev/ram max_loop=64 HARDWARE=virtual quiet
console= SR_BOOT=bootflash:packages.conf
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   5a9df20c:2bdc8144:e338d382:5a385d2c:43e05be2
        expected     5a9df20c:2bdc8144:e338d382:5a385d2c:43e05be2
package header rev 3 structure detected
IOSXE version 17.3.05 detected
Calculating SHA-1 hash...
2023-06-22 21:01:05,637: launch     TRACE    OUTPUT: done
SHA-1 hash:
        calculated   9dca816c:6b53eecd:a103d205:28e4e484:b8284ccf
        expected     9dca816c:6b53eecd:a103d205:28e4e484:b8284ccf
Package type:0x7531, flags:0x0
linux image, size=0x688dc8

2023-06-22 21:01:07,640: launch     TRACE    OUTPUT: linux isord, size=0x27a69a6


2023-06-22 21:01:09,643: launch     TRACE    OUTPUT: %IOSXEBOOT-4-PART_VERIFY: (local/local): Verifying partition table for device /dev/bootflash...
%IOSXEBOOT-4-PART_VERIFY: (local/local): Selected MBR v2 partition layout.

2023-06-22 21:01:25,671: launch     TRACE    OUTPUT: 
*Jun 22 21:01:24.364: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Checking for grub upgrade

*Jun 22 21:01:24.546: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Checking grub versions 2.2 vs 2.2

*Jun 22 21:01:24.550: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Bootloader upgrade not necessary.

2023-06-22 21:01:41,690: launch     TRACE    OUTPUT: Jun 22 21:01:40.425: %BOOT-5-OPMODE_LOG: R0/0: binos: System booted in AUTONOMOUS mode

2023-06-22 21:02:09,723: launch     TRACE    OUTPUT: 
              Restricted Rights Legend

Use, duplication, or disclosure by the Government is
subject to restrictions as set forth in subparagraph
(c) of the Commercial Computer Software - Restricted
Rights clause at FAR sec. 52.227-19 and subparagraph
(c) (1) (ii) of the Rights in Technical Data and Computer
Software clause at DFARS sec. 252.227-7013.

           Cisco Systems, Inc.
           170 West Tasman Drive
           San Jose, California 95134-1706



Cisco IOS Software [Amsterdam], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.3.5, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2022 by Cisco Systems, Inc.
Compiled Wed 09-Feb-22 10:35 by mcpre


This software version supports only Smart Licensing as the software licensing mechanism.


PLEASE READ THE FOLLOWING TERMS CAREFULLY. INSTALLING THE LICENSE OR
LICENSE KEY PROVIDED FOR ANY CISCO SOFTWARE PRODUCT, PRODUCT FEATURE,
AND/OR SUBSEQUENTLY PROVIDED SOFTWARE FEATURES (COLLECTIVELY, THE
"SOFTWARE"), AND/OR USING SUCH SOFTWARE CONSTITUTES YOUR FULL
ACCEPTANCE OF THE FOLLOWING TERMS. YOU MUST NOT PROCEED FURTHER IF YOU
ARE NOT WILLING TO BE BOUND BY ALL THE TERMS SET FORTH HEREIN.

Your use of the Software is subject to the Cisco End User License Agreement
(EULA) and any relevant supplemental terms (SEULA) found at
http://www.cisco.com/c/en/us/about/legal/cloud-and-software/software-terms.html.

You hereby acknowledge and agree that certain Software and/or features are
licensed for a particular term, that the license to such Software and/or
features is valid only for the applicable term and that such Software and/or
features may be shut down or otherwise terminated by Cisco after expiration
of the applicable license term (e.g., 90-day trial period). Cisco reserves
the right to terminate any such Software feature electronically or by any
other means available. While Cisco may provide alerts, it is your sole
responsibility to monitor your usage of any such term Software feature to
ensure that your systems and networks are prepared for a shutdown of the
Software feature.



2023-06-22 21:02:15,731: launch     TRACE    OUTPUT: 
All TCP AO KDF Tests Pass
cisco CSR1000V (VXE) processor (revision VXE) with 2071712K/3075K bytes of memory.
2023-06-22 21:02:17,734: launch     TRACE    OUTPUT: 
Processor board ID 9PGS3NGHOOR
Router operating mode: Autonomous
10 Gigabit Ethernet interfaces
32768K bytes of non-volatile configuration memory.
3978416K bytes of physical memory.
6188032K bytes of virtual hard disk at bootflash:.

2023-06-22 21:02:22,740: launch     DEBUG    matched, Press RETURN to get started.
2023-06-22 21:02:22,741: vrnetlab   DEBUG    writing to serial console: 
2023-06-22 21:02:22,741: launch     INFO     applying bootstrap configuration
2023-06-22 21:02:22,741: vrnetlab   DEBUG    writing to serial console: 
2023-06-22 21:02:22,741: vrnetlab   TRACE    waiting for '>' on serial console
2023-06-22 21:02:23,368: vrnetlab   TRACE    read from serial console: 


*Jun 22 21:02:09.751: %VUDI-6-EVENT: [serial number: 9PGS3NGHOOR], [vUDI: ], vUDI is successfully retrieved from license file
*Jun 22 21:02:09.790: %SMART_LIC-6-EXPORT_CONTROLLED: Usage of export controlled features is not allowed
*Jun 22 21:02:10.072: VXE-CSL-DBG:Unable to open the postFR backup file/file not present 

*Jun 22 21:02:10.198: %SMART_LIC-6-AGENT_READY: Smart Agent for Licensing is initialized
*Jun 22 21:02:10.198: %SMART_LIC-6-AGENT_ENABLED: Smart Agent for Licensing is enabled 
*Jun 22 21:02:10.198: %SMART_LIC-6-EXPORT_CONTROLLED: Usage of export controlled features is not allowed
*Jun 22 21:02:10.221: %VXE_THROUGHPUT-6-LEVEL: Throughput level has been set to 1000 kbps
*Jun 22 21:02:13.190: %VUDI-6-EVENT: [serial number: 9PGS3NGHOOR], [vUDI: CSR1000V:9PGS3NGHOOR], vUDI initialization is now complete
*Jun 22 21:02:13.245: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1, changed state to down
*Jun 22 21:02:13.249: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2, changed state to down
*Jun 22 21:02:13.254: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet3, changed state to down
*Jun 22 21:02:13.279: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet4, changed state to down
*Jun 22 21:02:13.311: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet5, changed state to down
*Jun 22 21:02:13.340: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet6, changed state to down
*Jun 22 21:02:13.347: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet7, changed state to down
*Jun 22 21:02:13.377: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet8, changed state to down
*Jun 22 21:02:13.406: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet9, changed state to down
*Jun 22 21:02:13.433: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet10, changed state to down
*Jun 22 21:02:13.473: BFD: brace register success
*Jun 22 21:02:14.623: %SPANTREE-5-EXTENDED_SYSID: Extended SysId enabled for type vlan
*Jun 22 21:02:14.689: %CRYPTO_ENGINE-4-CSDL_COMPLIANCE_DISABLED: Cisco PSB security compliance has been disabled
*Jun 22 21:02:14.718: %CUBE-3-LICENSING:  SIP trunking (CUBE) licensing is now based on dynamic sessions counting, static license capacity configuration through 'mode border-element license capacity' would be ignored.
*Jun 22 21:02:14.721: %SIP-5-LICENSING: CUBE license reporting period has been set to the minimum value of 8 hours.
*Jun 22 21:02:14.722: %VOICE_HA-7-STATUS: CUBE HA-supported platform detected.
*Jun 22 21:02:14.890: %LINK-3-UPDOWN: Interface Lsmpi0, changed state to up
*Jun 22 21:02:14.933: %LINK-3-UPDOWN: Interface EOBC0, changed state to up
*Jun 22 21:02:14.935: %LINEPROTO-5-UPDOWN: Line protocol on Interface LI-Null0, changed state to up
*Jun 22 21:02:14.935: %LINEPROTO-5-UPDOWN: Line protocol on Interface VoIP-Null0, changed state to up
*Jun 22 21:02:15.153: %PNP-6-PNP_DISCOVERY_STARTED: PnP Discovery started
*Jun 22 21:01:40.420: %BOOT-5-OPMODE_LOG: R0/0: binos: System booted in AUTONOMOUS mode
*Jun 22 21:01:56.451: %CPPDRV-4-CPU_FEATURE: R0/0: cpp_driver: CPP0: CPU lacks feature (Population Count HW-Assist (POPCNT)).  Performance may be sub-optimal.
*Jun 22 21:01:56.452: %CPPDRV-4-CPU_FEATURE: R0/0: cpp_driver: CPP0: CPU lacks feature (AES HW-Assist (AES-NI)).  Performance may be sub-optimal.
*Jun 22 21:01:56.452: %CPPDRV-3-GUEST_CPU_FEATURE: R0/0: cpp_driver: CPP0: Guest CPU lacks feature (Supplemental Streaming SIMD Extensions 3 (SSSE3)).
*Jun 22 21:01:56.452: %CPPDRV-4-CPU_FEATURE: R0/0: cpp_driver: CPP0: CPU lacks feature (Streaming SIMD Extensions 4.1 (SSE4.1)).  Performance may be sub-optimal.
*Jun 22 21:01:56.452: %CPPDRV-4-CPU_FEATURE: R0/0: cpp_driver: CPP0: CPU lacks feature (Streaming SIMD Extensions 4.2 (SSE4.2)).  Performance may be sub-optimal.
*Jun 22 21:02:15.449: %SMART_LIC-6-HA_ROLE_CHANGED: Smart Agent HA role changed to Active.
*Jun 22 21:02:15.795: %LINK-3-UPDOWN: Interface LIIN0, changed state to up
*Jun 22 21:02:15.800: %LINK-3-UPDOWN: Interface GigabitEthernet1, changed state to down
*Jun 22 21:02:15.810: %LINK-3-UPDOWN: Interface GigabitEthernet2, changed state to down
*Jun 22 21:02:15.813: %LINK-3-UPDOWN: Interface GigabitEthernet3, changed state to down
*Jun 22 21:02:15.818: %LINK-3-UPDOWN: Interface GigabitEthernet4, changed state to down
*Jun 22 21:02:15.820: %LINK-3-UPDOWN: Interface GigabitEthernet5, changed state to down
*Jun 22 21:02:15.822: %LINK-3-UPDOWN: Interface GigabitEthernet6, changed state to down
*Jun 22 21:02:15.827: %LINK-3-UPDOWN: Interface GigabitEthernet7, changed state to down
*Jun 22 21:02:15.829: %LINK-3-UPDOWN: Interface GigabitEthernet8, changed state to down
*Jun 22 21:02:15.832: %LINK-3-UPDOWN: Interface GigabitEthernet9, changed state to down
*Jun 22 21:02:15.833: %LINK-3-UPDOWN: Interface GigabitEthernet10, changed state to down
*Jun 22 21:02:15.905: %LINEPROTO-5-UPDOWN: Line protocol on Interface Lsmpi0, changed state to up
*Jun 22 21:02:16.163: %LINEPROTO-5-UPDOWN: Line protocol on Interface EOBC0, changed state to up
*Jun 22 21:02:16.504: %SYS-7-NVRAM_INIT_WAIT_TIME: Waited 0 seconds for NVRAM to be available
*Jun 22 21:02:16.591: %CRYPTO_ENGINE-5-KEY_ADDITION: A key named TP-self-signed-3258203010 has been generated or imported by crypto config
*Jun 22 21:02:16.631: %PKI-6-TRUSTPOINT_CREATE: Trustpoint: TP-self-signed-3258203010 created succesfully
*Jun 22 21:02:16.633: %PKI-6-TRUSTPOINT_CREATE: Trustpoint: SLA-TrustPoint created succesfully
*Jun 22 21:02:16.798: %SYS-5-CONFIG_I: Configured from memory by console
*Jun 22 21:02:16.936: %SYS-5-RESTART: System restarted --
Cisco IOS Software [Amsterdam], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.3.5, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2022 by Cisco Systems, Inc.
Compiled Wed 09-Feb-22 10:35 by mcpre
*Jun 22 21:02:17.170: %IOSXE_OIR-6-INSCARD: Card (fp) inserted in slot F0
*Jun 22 21:02:17.170: %IOSXE_OIR-6-ONLINECARD: Card (fp) online in slot F0
*Jun 22 21:02:17.290: %LINEPROTO-5-UPDOWN: Line protocol on Interface LIIN0, changed state to up
*Jun 22 21:02:17.290: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1, changed state to down
*Jun 22 21:02:17.290: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2, changed state to down
*Jun 22 21:02:17.291: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet3, changed state to down
*Jun 22 21:02:17.292: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet4, changed state to down
*Jun 22 21:02:17.292: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet5, changed state to down
*Jun 22 21:02:17.293: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet6, changed state to down
*Jun 22 21:02:17.293: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet7, changed state to down
*Jun 22 21:02:17.293: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet8, changed state to down
*Jun 22 21:02:17.293: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet9, changed state to down
*Jun 22 21:02:17.293: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet10, changed state to down
*Jun 22 21:02:17.316: %SSH-5-ENABLED: SSH 1.99 has been enabled
*Jun 22 21:02:17.369: %CRYPTO-6-ISAKMP_ON_OFF: ISAKMP is OFF
*Jun 22 21:02:17.369: %CRYPTO-6-GDOI_ON_OFF: GDOI is OFF
*Jun 22 21:02:17.701: %ONEP_BASE-6-SS_ENABLED: ONEP: Service set Base was enabled by Default
*Jun 22 21:02:18.662: %LINK-5-CHANGED: Interface GigabitEthernet1, changed state to administratively down
*Jun 22 21:02:18.687: %LINK-5-CHANGED: Interface GigabitEthernet2, changed state to administratively down
*Jun 22 21:02:18.688: %LINK-5-CHANGED: Interface GigabitEthernet3, changed state to administratively down
*Jun 22 21:02:18.725: %LINK-5-CHANGED: Interface GigabitEthernet4, changed state to administratively down
*Jun 22 21:02:18.726: %LINK-5-CHANGED: Interface GigabitEthernet5, changed state to administratively down
Router>
2023-06-22 21:02:23,368: vrnetlab   DEBUG    writing to serial console: enable
2023-06-22 21:02:23,368: vrnetlab   TRACE    waiting for '>' on serial console
2023-06-22 21:02:23,368: vrnetlab   TRACE    read from serial console: 
Router>
2023-06-22 21:02:23,368: vrnetlab   DEBUG    writing to serial console: configure terminal
2023-06-22 21:02:23,368: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,412: vrnetlab   TRACE    read from serial console: enable
Router#
2023-06-22 21:02:23,412: vrnetlab   DEBUG    writing to serial console: hostname csr1000v
2023-06-22 21:02:23,412: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,412: vrnetlab   TRACE    read from serial console: configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
Router(config)#
2023-06-22 21:02:23,412: vrnetlab   DEBUG    writing to serial console: username vrnetlab privilege 15 password VR-netlab9
2023-06-22 21:02:23,412: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,456: vrnetlab   TRACE    read from serial console: hostname csr1000v
csr1000v(config)#
2023-06-22 21:02:23,456: vrnetlab   DEBUG    writing to serial console: ip domain-name example.com
2023-06-22 21:02:23,456: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,456: vrnetlab   TRACE    read from serial console: username vrnetlab privilege 15 password VR-netlab9
 WARNING: Command has been added to the configuration using a type 0 password. However, type 0 passwords will soon be deprecated. Migrate to a supported password type
csr1000v(config)#
2023-06-22 21:02:23,456: vrnetlab   DEBUG    writing to serial console: crypto key generate rsa modulus 2048
2023-06-22 21:02:23,456: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,500: vrnetlab   TRACE    read from serial console: ip domain-name example.com
                          ^
% Invalid input detected at '^' marker.

csr1000v(config)#
2023-06-22 21:02:23,500: vrnetlab   DEBUG    writing to serial console: interface GigabitEthernet1
2023-06-22 21:02:23,500: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,500: vrnetlab   TRACE    read from serial console: crypto key generate rsa modulus 2048
% Please define a domain-name first.
csr1000v(config)#
2023-06-22 21:02:23,500: vrnetlab   DEBUG    writing to serial console: ip address 10.0.0.15 255.255.255.0
2023-06-22 21:02:23,500: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,544: vrnetlab   TRACE    read from serial console: interface GigabitEthernet1
csr1000v(config-if)#
2023-06-22 21:02:23,544: vrnetlab   DEBUG    writing to serial console: no shut
2023-06-22 21:02:23,544: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,544: vrnetlab   TRACE    read from serial console: ip address 10.0.0.15 255.255.255.0
csr1000v(config-if)#
2023-06-22 21:02:23,544: vrnetlab   DEBUG    writing to serial console: exit
2023-06-22 21:02:23,544: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,588: vrnetlab   TRACE    read from serial console: no shut
csr1000v(config-if)#
2023-06-22 21:02:23,588: vrnetlab   DEBUG    writing to serial console: restconf
2023-06-22 21:02:23,588: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,588: vrnetlab   TRACE    read from serial console: exit
csr1000v(config)#
2023-06-22 21:02:23,588: vrnetlab   DEBUG    writing to serial console: netconf-yang
2023-06-22 21:02:23,588: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,632: vrnetlab   TRACE    read from serial console: restconf
csr1000v(config)#
2023-06-22 21:02:23,632: vrnetlab   DEBUG    writing to serial console: line vty 0 4
2023-06-22 21:02:23,632: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,632: vrnetlab   TRACE    read from serial console: netconf-yang
csr1000v(config)#
2023-06-22 21:02:23,632: vrnetlab   DEBUG    writing to serial console: login local
2023-06-22 21:02:23,632: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,676: vrnetlab   TRACE    read from serial console: line vty 0 4
csr1000v(config-line)#
2023-06-22 21:02:23,676: vrnetlab   DEBUG    writing to serial console: transport input all
2023-06-22 21:02:23,676: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,676: vrnetlab   TRACE    read from serial console: login local
csr1000v(config-line)#
2023-06-22 21:02:23,676: vrnetlab   DEBUG    writing to serial console: end
2023-06-22 21:02:23,676: vrnetlab   TRACE    waiting for '#' on serial console
2023-06-22 21:02:23,720: vrnetlab   TRACE    read from serial console: transport input all
csr1000v(config-line)#
2023-06-22 21:02:23,720: vrnetlab   DEBUG    writing to serial console: copy running-config startup-config
2023-06-22 21:02:23,720: vrnetlab   DEBUG    writing to serial console: 
2023-06-22 21:02:23,720: launch     INFO     Startup complete in: 0:01:28.099230







Image build
=
`BOOT CMD: /packages.conf rw root=/dev/ram max_loop=64 HARDWARE=virtual quiet
console= SR_BOOT=bootflash:packages.conf
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   5a9df20c:2bdc8144:e338d382:5a385d2c:43e05be2
        expected     5a9df20c:2bdc8144:e338d382:5a385d2c:43e05be2
package header rev 3 structure detected
IOSXE version 17.3.05 detected
Calculating SHA-1 hash...
2023-06-22 20:51:53,365: launch     TRACE    OUTPUT: done
SHA-1 hash:
        calculated   9dca816c:6b53eecd:a103d205:28e4e484:b8284ccf
        expected     9dca816c:6b53eecd:a103d205:28e4e484:b8284ccf
Package type:0x7531, flags:0x0
linux image, size=0x688dc8

2023-06-22 20:51:55,368: launch     TRACE    OUTPUT: linux isord, size=0x27a69a6


2023-06-22 20:51:57,369: launch     TRACE    OUTPUT: %IOSXEBOOT-4-PART_SEEDNVRAM: (local/local): Seeding nvram [SUCCESS]
%IOSXEBOOT-4-PART_VERIFY: (local/local): Verifying partition table for device /dev/bootflash...
%IOSXEBOOT-4-PART_VERIFY: (local/local): Selected MBR v2 partition layout.
%IOSXEBOOT-4-SETUP_CRYPTO: (local/local): Formatting /dev/sda7
%IOSXEBOOT-4-SETUP_CRYPTO: (local/local): Formatting /dev/sda9
%IOSXEBOOT-4-SETUP_CRYPTO: (local/local): Formatting /dev/sda2
%IOSXEBOOT-4-SETUP_CRYPTO: (local/local): Formatting /dev/sda6
%IOSXEBOOT-4-SETUP_CRYPTO: (local/local): Formatting /dev/sda8
%IOSXEBOOT-4-SETUP_CRYPTO: (local/local): Formatting /dev/sda10

2023-06-22 20:52:41,415: launch     TRACE    OUTPUT: %IOSXEBOOT-4-FILESYS_INVALID: (local/local): partition /dev/mapper/csl_p_1 has an invalid filesystem that must be re-initialized.
%IOSXEBOOT-4-FILESYS_INVALID: (local/local): partition /dev/mapper/csl_s_1 has an invalid filesystem that must be re-initialized.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): The system will repair /dev/mapper/csl_s_1 now.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): The system will repair /dev/mapper/csl_p_1 now.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): This will cause a complete loss of data.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): This will cause a complete loss of data.
%IOSXEBOOT-4-FILESYS_INVALID: (local/local): partition /dev/mapper/csl_s_0 has an invalid filesystem that must be re-initialized.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): The system will repair /dev/mapper/csl_s_0 now.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): This will cause a complete loss of data.
%IOSXEBOOT-4-FILESYS_INVALID: (local/local): partition /dev/mapper/config has an invalid filesystem that must be re-initialized.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): The system will repair /dev/mapper/config now.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): This will cause a complete loss of data.
%IOSXEBOOT-4-FILESYS_INVALID: (local/local): partition /dev/mapper/csl_p_0 has an invalid filesystem that must be re-initialized.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): The system will repair /dev/mapper/csl_p_0 now.
%IOSXEBOOT-4-FILESYS_REPAIR: (local/local): This will cause a complete loss of data.

2023-06-22 20:52:45,420: launch     TRACE    OUTPUT: 
*Jun 22 20:52:43.629: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Checking for grub upgrade

*Jun 22 20:52:43.790: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Checking grub versions 2.2 vs 2.2

*Jun 22 20:52:43.793: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Bootloader upgrade not necessary.

2023-06-22 20:53:01,439: launch     TRACE    OUTPUT: Jun 22 20:53:00.218: %BOOT-5-OPMODE_LOG: R0/0: binos: System booted in AUTONOMOUS mode

2023-06-22 20:53:29,468: launch     TRACE    OUTPUT: 
              Restricted Rights Legend

Use, duplication, or disclosure by the Government is
subject to restrictions as set forth in subparagraph
(c) of the Commercial Computer Software - Restricted
Rights clause at FAR sec. 52.227-19 and subparagraph
(c) (1) (ii) of the Rights in Technical Data and Computer
Software clause at DFARS sec. 252.227-7013.

           Cisco Systems, Inc.
           170 West Tasman Drive
           San Jose, California 95134-1706



Cisco IOS Software [Amsterdam], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.3.5, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2022 by Cisco Systems, Inc.
Compiled Wed 09-Feb-22 10:35 by mcpre


This software version supports only Smart Licensing as the software licensing mechanism.


PLEASE READ THE FOLLOWING TERMS CAREFULLY. INSTALLING THE LICENSE OR
LICENSE KEY PROVIDED FOR ANY CISCO SOFTWARE PRODUCT, PRODUCT FEATURE,
AND/OR SUBSEQUENTLY PROVIDED SOFTWARE FEATURES (COLLECTIVELY, THE
"SOFTWARE"), AND/OR USING SUCH SOFTWARE CONSTITUTES YOUR FULL
ACCEPTANCE OF THE FOLLOWING TERMS. YOU MUST NOT PROCEED FURTHER IF YOU
ARE NOT WILLING TO BE BOUND BY ALL THE TERMS SET FORTH HEREIN.

Your use of the Software is subject to the Cisco End User License Agreement
(EULA) and any relevant supplemental terms (SEULA) found at
http://www.cisco.com/c/en/us/about/legal/cloud-and-software/software-terms.html.

You hereby acknowledge and agree that certain Software and/or features are
licensed for a particular term, that the license to such Software and/or
features is valid only for the applicable term and that such Software and/or
features may be shut down or otherwise terminated by Cisco after expiration
of the applicable license term (e.g., 90-day trial period). Cisco reserves
  Booting `CSR1000v - packages.conf'


BOOT CMD: /packages.conf rw root=/dev/ram max_loop=64 HARDWARE=virtual quiet
console= SR_BOOT=bootflash:packages.conf
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   5a9df20c:2bdc8144:e338d382:5a385d2c:43e05be2
        expected     5a9df20c:2bdc8144:e338d382:5a385d2c:43e05be2
package header rev 3 structure detected
IOSXE version 17.3.05 detected
Calculating SHA-1 hash...
2023-06-22 20:53:57,493: launch     TRACE    OUTPUT: done
SHA-1 hash:
        calculated   9dca816c:6b53eecd:a103d205:28e4e484:b8284ccf
        expected     9dca816c:6b53eecd:a103d205:28e4e484:b8284ccf
Package type:0x7531, flags:0x0
linux image, size=0x688dc8
linux isord, size=0x27a69a6


2023-06-22 20:53:59,495: launch     TRACE    OUTPUT: %IOSXEBOOT-4-PART_VERIFY: (local/local): Verifying partition table for device /dev/bootflash...
%IOSXEBOOT-4-PART_VERIFY: (local/local): Selected MBR v2 partition layout.

https://github.com/vrnetlab/vrnetlab/discussions/3002023-06-22 20:54:17,515: launch     TRACE    OUTPUT: 
*Jun 22 20:54:16.050: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Checking for grub upgrade

*Jun 22 20:54:16.201: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Checking grub versions 2.2 vs 2.2

*Jun 22 20:54:16.204: %IOSXEBOOT-4-BOOT_SRC: (rp/0): Bootloader upgrade not necessary.

2023-06-22 20:54:33,532: launch     TRACE    OUTPUT: Jun 22 20:54:32.259: %BOOT-5-OPMODE_LOG: R0/0: binos: System booted in AUTONOMOUS mode
`

**Comment by mzagozen** [comment]
@bvilajol your issue is still valid. With v16 and onwards the `ip domain-name FOO` was changed to `ip domain name FOO`.

You can see that in your boot log too, after the `ip domain-name example.com` command fails to apply, `crypto key generate rsa modulus 2048` also fails and that results in no host key generated meaning SSH server won't run.

I'll push a fix to handle different versions shortly.

**Comment by bvilajol** [comment]
@mzagozen  thanks, good to know. btw, wondering if bootstrap config requires 'ip scp server enable' as per NETCONF availability.
Thanks!
