### ISSUE TITLE
IpInfusion OcNOS changed vm filename

### ISSUE THREAD

**Issue by TomBuyvoets** [vrnetlab/vrnetlab#319]
IPInfusion OcNOS changed vm filename to something like`OcNOS-SP-MPLS-x86-6.3.0-126-GA.qcow2`.

The makefile expects something like `DEMO_VM-OcNOS-6.0.2.11-MPLS-x86-MR.qcow2`.

If you now run `make docker-image` you get error: `ERROR: invalid tag "vrnetlab/vr-ocnos:": invalid reference format`.

You can solve this issue by changing regex in sed command like `sed -rn 's/OcNOS-SP-MPLS-x86-(.+).*.qcow/\1/p'`

This is the final Makefile I used:

```
VENDOR=IPInfusion
NAME=OcNOS
IMAGE_FORMAT=qcow2
IMAGE_GLOB=*.qcow2

# match versions like:
# OcNOS-SP-MPLS-x86-6.3.0-126-GA.qcow2
VERSION=$(shell echo $(IMAGE) | sed -rn 's/OcNOS-SP-MPLS-x86-(.+).*.qcow/\1/p')

-include ../makefile-sanity.include
-include ../makefile.include
```

unfortunately I'm not able to create a pull request.

**Comment by plajjan** [comment]
Is this a platform type in this repo or a has it been added separately?

**Comment by plajjan** [comment]
I don't think this is relevant for this repo. You are likely to have some custom platform. Closing this. Feel free to reopen with more information or so.
