### ISSUE TITLE
xcon-ng segfault when connecting to many (unreachable) devices

### ISSUE THREAD

**Issue by mzagozen** [vrnetlab/vrnetlab#321]
I've been testing the acton implementation of xcon-ng in one of my projects. So far it has been stable, but today I added more devices to the network and thus increased the number of p2p links. I got the following segfault. I am not sure why xcon-ng could not resolve the new hostnames. The new containers were definitely running (script starts them before xcon), but maybe docker internal DNS needed some time to update? Anyway, it looks like there is something fishy going on when xcon-ng is faced with many DNS resolution failures.

Unfortunately I don't have a detailed stack trace or core dump because there were no debug tools installed in the container.
[xcon-ng-dns-segfault.log](https://github.com/vrnetlab/vrnetlab/files/11958432/xcon-ng-dns-segfault.log)

```
[ ... log excrept ...]
healthcheck: 1 (Expected 18 sockets but only 17 connected)
Resolved pc-2 to 172.26.0.12
xcon: /__w/acton/acton/dist/deps/libuv/src/unix/stream.c:1158: int uv_shutdown(uv_shutdown_t *, uv_stream_t *, uv_shutdown_cb): Assertion `stream->type == UV_TCP || stream->type == UV_TTY || stream->type == UV_NAMED_PIPE' failed.

ERROR: segmentation fault
NOTE: this is likely a bug in acton, please report this at:
NOTE: https://github.com/actonlang/acton/issues/new
NOTE: include the backtrace printed below between -- 8< -- lines

-- 8< --------- BACKTRACE --------------------
healthcheck: 1 (Expected 18 sockets but only 17 connected)
TCP Client connection established to pc-2/1
healthcheck: 0 (All 18 sockets connected)
Unable to get detailed backtrace using lldb or gdb
-- 8< --------- END BACKTRACE ----------------

ERROR: segmentation fault
NOTE: this is likely a bug in acton, please report this at:
NOTE: https://github.com/actonlang/acton/issues/new
NOTE: include the backtrace printed above between -- 8< -- lines
```

**Comment by mzagozen** [comment]
I scripted the equivalent test of creating the containers and xcon-ng in a loop for the past few hours, but could not reproduce. Cosmic radiation?

**Comment by plajjan** [comment]
Hmm, the assert is pretty clear at least, so there's that. I'm actually a little surprised we get an assert. Is this a --dev build? Thought they would be optimized away.

Probability of cosmic radiation is low. segfaults sort of don't lie, if they happened once I think it's likely there is a bug and it will happen again. Maybe the details of the bug are so fine that your reproduction attempt is too far from what's needed to actually reproduce the bug.

I attempted to "stare down" the bug but failed. I've looked at the source code and cannot see how we can end up calling uv_shutdown with an argument that is not of type UV_TCP. I will have to stare at it some more, I suppose.

Could you enable core dumps, that way we'll have way better diagnostics the next time this happens.

**Comment by mzagozen** [comment]
I enabled core dumps in the container, ran the tests for many more hours, still nothing 🤷

**Comment by mzagozen** [comment]
Used `xcon-ng` a bunch, but have only seen this error the once. I will reopen if it pops up again I guess.
