### ISSUE TITLE
CSR 1000v not able to communicate

### ISSUE THREAD

**Issue by sebaz9130** [vrnetlab/vrnetlab#324]
Hi guys I really appreciate the work you have done here. I built a couple of containers based on CSR1000v connecting each other, the topology went up correctly but after configuring the CSR devices they are not able to ping each other.

Linux Ubuntu Ubuntu 20.04.6 LTS
Containerlab 0.42.0
Docker 20.10.21
CSR1000v 16.12.05, 17.03.02

**Comment by mzagozen** [comment]
Hi @sebaz9130, I see you mention containerlab. That project is located in https://github.com/srl-labs/containerlab and the vrnetlab fork it uses in https://github.com/hellt/vrnetlab. Please open an issue in the containerlab repository, and provide the full topology definition file (`*.clab.yml`) as reference.

**Comment by mzagozen** [comment]
Oh, I see you already did that: https://github.com/srl-labs/containerlab/issues/1459 :)
Closing this one.
