### ISSUE TITLE
AOSCX - Launch.py exec permission missing 

### ISSUE THREAD

**Issue by Sadiqbk** [vrnetlab/vrnetlab#345]
VRNETLAB launc.py is not able to start AOSCX in AOS containerLAB

https://discord.com/channels/860500297297821756/1238479389394473050

![image](https://github.com/vrnetlab/vrnetlab/assets/22385746/4599f1f6-214b-433f-8758-b9022402a18e)

[root@cLAB vrnetlab-0.16.0]# cd aoscx/
[root@cLAB aoscx]# cd docker/
[root@cLAB docker]# ls -al
total 386128
drwxr-xr-x. 2 root root       144 May 11 18:08 .
drwxr-xr-x. 3 root root       115 May 11 17:29 ..
-rw-r--r--. 1 root root 395342848 May 11 18:08 arubaoscx-disk-image-genericx86-p4-20240129204649.vmdk
-rw-r--r--. 1 root root       614 Apr  4 03:38 Dockerfile
-rw-r--r--. 1 root root       339 May 11 18:08 healthcheck.py
-rw-r--r--. 1 root root      6199 Apr  4 03:38 launch.py
-rw-r--r--. 1 root root     29356 May 11 18:08 vrnetlab.py
[root@cLAB docker]#

**Comment by mzagozen** [comment]
Hi @Sadiqbk, this repository does not support the AOS-CX platform. If you're still experiencing the problems described, please open an issue in https://github.com/hellt/vrnetlab
