### ISSUE TITLE
"failed to Statfs "/proc/0/ns/net": no such file or directory" error when using nxos 

### ISSUE THREAD

**Issue by nagraj-kulkarni** [vrnetlab/vrnetlab#353]
Hello, 

built a docker image for nxos with did not see any errors when building the docker image of nxos, but when i try to use this image with netlab, getting below error :

ERRO[0003] failed deploy links for node "router": failed to Statfs "/proc/0/ns/net": no such file or directory

Appreciate any pointers on this. built many other images but facing this only with nxos

**Comment by nagraj-kulkarni** [comment]
this is with vrnetlab/hellt

**Comment by hellt** [comment]
> this is with vrnetlab/hellt

then you should have opened it at https://github.com/hellt/vrnetlab/issues

**Comment by nagraj-kulkarni** [comment]
oh, my bad..will close this one
